### ISSUE TITLE
Any way to persist results?

### ISSUE THREAD

**Issue by xf-** [awinnen/ExpertPriceCrawler#5]
At the moment, the container uses a clean storage on every start. I would like to add a `volume`, so I get the old results and can press update.

Current  `docker-compose.yml` config
```yaml
version: '3.6'
services:
    expertpricecrawler:
        image: awinnen/expertpricecrawler:latest
        ports:
            - 8231:80 # Port 80 is in use and a reverse proxy is in use
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable
            - Serilog__MinimumLevel=Verbose
            - SmtpServer__From=noreply@domain.tld
            - SmtpServer__Hostname=mailserver.domain.tld
            - SmtpServer__Password=anyawesomepassword
            - SmtpServer__Port=587
            - SmtpServer__Username=anyusernameavailableonyourmailserver
            - SmtpServer__UseSsl=true
            - Logging__Console__FormatterName=json
            - Options__CrawlerType=BrowserCrawler
            - Options__MaxParallelRequests=5
            - Options__MemoryCacheMinutes=5
            - Options__RateLimitInMinutes=1

```
